---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: true


  vars_files:
    - rhvm_vars.yml
    - password.yml
    - host_vm_vars.yml


  pre_tasks:
    - name: Login to oVirt
      ovirt.ovirt.ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        ca_file: "{{ rhvm_cafile | default(omit) }}"
        password: "{{ engine_ password }}"
              
             
      tags:
        - always


  tasks:
  - name: Create and run VM from template
    ovirt.ovirt.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      high_availability: true
      state: running
      wait: yes
 
 
    - debug: var=hostvars[inventory_hostname]['ansible_enp0s3']['ipv4']['address']
    
    
  post_tasks:
    - name: Logout from oVirt
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

  collections:
    - ovirt.ovirt
