---
- name: Установка и настройка DHCP-сервера
  hosts: dhcp-servers
  become: true

  tasks:
    - name: Установка пакета dhcpd
      package:
        name: dhcpd
        state: present

    - name: Копирование конфигурационного файла dhcpd.conf
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Перезапуск DHCP-сервера
      service:
        name: dhcpd
        state: restarted
